### ISSUE TITLE
grunt sheets: Error: The caller does not have permission

### ISSUE THREAD

**Issue by raineorshine** [nprapps/book-concierge#74]
Hi! Thanks for making book-concierge open source. I am attempting to set it up locally.

I created a Google OAuth token with Drive and Sheets API's enabled. 

<img width="518" alt="Screen Shot 2020-06-14 at 5 04 57 PM" src="https://user-images.githubusercontent.com/750276/84606498-f8f4a780-ae63-11ea-8bdb-be556a0bf6c4.png">
<img width="427" alt="Screen Shot 2020-06-14 at 5 18 35 PM" src="https://user-images.githubusercontent.com/750276/84606501-fb570180-ae63-11ea-985b-1a2776071ccc.png">

I successfully ran `grunt google-auth` and  `grunt google-create --type=sheets --name="My Document Name"`. However when I run `grunt sheets` I get the following error: 

```
$ grunt sheets
Running "sheets" task
(node:30694) UnhandledPromiseRejectionWarning: Error: The caller does not have permission
```

Any ideas? Thanks!

**Comment by thomaswilburn** [comment]
Do you still have the original sheet in the project.json file? It may be trying to load the NPR data, which we do not make open to the public.

**Comment by raineorshine** [comment]
> Do you still have the original sheet in the project.json file? It may be trying to load the NPR data, which we do not make open to the public.

Yes, that was it! Thank you.
