### ISSUE TITLE
Support multiple reviewers

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/book-concierge#78]
This year we may have items where a book is reviewed by multiple people. We should be able to set the reviewer field to a comma-separated list, and have it output that as a set of linked name/title strings.

1. Update the shelving and validation code so that they support an array of reviewers, not a single reviewer.
2. Update the client-side code to join these reviewers in a loop.

**Comment by heyjessi** [comment]
pull request: https://github.com/nprapps/book-concierge/pull/85

**Comment by thomaswilburn** [comment]
Closed via: ac11a03
