### ISSUE TITLE
Support non-ISBN book images

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/book-concierge#79]
Currently we link images to books by using the ISBN as an implicit key. We should make that explicit, so that we can support non-ISBN image names (for books that are non-mainstream published works).

1. Create "cover" columns in the old sheet, and copy the ISBN into them.
2. Update the shelving code to propagate the cover column into the catalog JSON file.
3. Update the client-side code to look at the cover for creating the image tags.

**Comment by heyjessi** [comment]
filed a pull request here: https://github.com/nprapps/book-concierge/pull/84
