### ISSUE TITLE
Amazon scraper: Pull page numbers if available

### ISSUE THREAD

**Issue by alykat** [nprapps/book-concierge#95]
Useful for the books team to identify entries that would be tagged "rather long" or "rather short"

**Comment by alykat** [comment]
Beth reiterated her interest in such a feature. I briefly looked into the [amazon scraper code](https://github.com/nprapps/book-concierge/blob/master/tasks/amazon.js), and it looks like what we're saving out to the CSV is everything that's offered in the search return. Would need to take more time to figure out how to query additional metadata, if that's offered in this API.

**Comment by thomaswilburn** [comment]
I think this is actually available in the API: https://webservices.amazon.com/paapi5/documentation/item-info.html#contentinfo

If you look at the bottom of tasks/lib/amazon-product.js, you'll find the keys being extracted, and can add this.

**Comment by alykat** [comment]
Ahhh! I totally missed the second script in the lib folder. This did the trick. Thank you so much!
